CASES = [
    {
        "id": "CASE-2024-001",
        "name": "Yilmaz v. ABC Insurance Co.",
        "client": "Mehmet Yilmaz",
        "case_type": "Insurance Law",
        "status": "active",
        "attachments": [
            {"id": "att-001", "name": "Statement_of_Claim_Yilmaz.pdf"},
            {"id": "att-002", "name": "Insurance_Policy_4478.pdf"},
            {"id": "att-003", "name": "Damage_Assessment_Report.pdf"},
            {"id": "att-004", "name": "Witness_Statement_Kaya.docx"},
        ],
    },
    {
        "id": "CASE-2024-002",
        "name": "Demir Holding - Merger Agreement",
        "client": "Demir Holding Inc.",
        "case_type": "Corporate Law",
        "status": "active",
        "attachments": [
            {"id": "att-005", "name": "Merger_Protocol_Draft.pdf"},
            {"id": "att-006", "name": "Due_Diligence_Report.pdf"},
            {"id": "att-007", "name": "Board_Resolution.pdf"},
            {"id": "att-008", "name": "SEC_Filing_Documents.pdf"},
            {"id": "att-009", "name": "Financial_Statements_2024.xlsx"},
        ],
    },
    {
        "id": "CASE-2024-003",
        "name": "Aksoy - Employment Termination Dispute",
        "client": "Ayse Aksoy",
        "case_type": "Employment Law",
        "status": "active",
        "attachments": [
            {"id": "att-010", "name": "Employment_Contract.pdf"},
            {"id": "att-011", "name": "Termination_Notice.pdf"},
            {"id": "att-012", "name": "Payroll_Records_2023_2024.xlsx"},
            {"id": "att-013", "name": "Social_Security_Service_Record.pdf"},
        ],
    },
    {
        "id": "CASE-2024-004",
        "name": "Ozturk Family - Inheritance Distribution",
        "client": "Fatma Ozturk",
        "case_type": "Inheritance Law",
        "status": "pending",
        "attachments": [
            {"id": "att-014", "name": "Certificate_of_Inheritance.pdf"},
            {"id": "att-015", "name": "Land_Registry_Records_Kadikoy.pdf"},
            {"id": "att-016", "name": "Last_Will_and_Testament.pdf"},
            {"id": "att-017", "name": "Real_Estate_Appraisal_Report.pdf"},
            {"id": "att-018", "name": "Heir_List_and_Shares.docx"},
        ],
    },
    {
        "id": "CASE-2024-005",
        "name": "TechSoft Ltd. - Patent Infringement",
        "client": "TechSoft Software Ltd.",
        "case_type": "Intellectual Property Law",
        "status": "active",
        "attachments": [
            {"id": "att-019", "name": "Patent_Certificate_TR_2021_04892.pdf"},
            {"id": "att-020", "name": "Infringement_Detection_Report.pdf"},
            {"id": "att-021", "name": "Technical_Expert_Report.pdf"},
            {"id": "att-022", "name": "Opposing_Party_Product_Analysis.pdf"},
        ],
    },
    {
        "id": "CASE-2024-006",
        "name": "Celik Construction - Zoning Plan Appeal",
        "client": "Celik Construction Inc.",
        "case_type": "Administrative Law",
        "status": "active",
        "attachments": [
            {"id": "att-023", "name": "Zoning_Plan_Amendment_Decision.pdf"},
            {"id": "att-024", "name": "Appeal_Petition.pdf"},
            {"id": "att-025", "name": "Environmental_Impact_Assessment.pdf"},
            {"id": "att-026", "name": "Municipal_Council_Decision.pdf"},
            {"id": "att-027", "name": "Land_Title_Deed.pdf"},
        ],
    },
]

CASES_BY_ID = {case["id"]: case for case in CASES}
